# docker/docker-compose.yml
version: '3.9'

networks:
  database:
  database-test:

services:
  reminder-test:
    build:
      context: ./build/dockerfiles/golang
      target: golang_test
    volumes:
      - ./src:/go/src
    networks:
      - database

  reminder-dev: &dev
    build:
      context: ./build/dockerfiles/golang
      target: golang_dev
    ports:
      - "8080:8080"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    networks:
      - database-test

  reminder-prod:
    <<: *dev
    build:
      context: ./build/dockerfiles/golang
      target: golang_prod
    networks:
      - database

  reminder-database: &database
    container_name: gateway-database
    build: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - database

  reminder-database-test:
    <<: *database
    networks:
      - database-test